/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mangri.sample.servlet;

import static org.junit.Assert.assertEquals;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.container.test.api.RunAsClient;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(Arquillian.class)
public class SampleServletIT {
    @Deployment(testable = false)
    public static WebArchive deploy() {
        return ShrinkWrap.create(WebArchive.class, "sample.war")
            .addClass(SampleServlet.class);
    }

    @Test @RunAsClient
    public void succeeds() throws Exception {
        URL url = new URL("http://127.0.0.1:8080/sample/check");
        try (InputStream is = url.openStream()) {
            String response = new BufferedReader(new InputStreamReader(is)).readLine();
            assertEquals("yes it works", response);
        }
    }

}
