/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mangri.sample.servlet;

import static org.junit.Assert.assertEquals;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(Arquillian.class)
public class SampleServletTest {
    @Deployment
    public static WebArchive deployment() {
        return ShrinkWrap.create(WebArchive.class, "sample.war")
            .addClass(SampleServlet.class);
    }


    @Test 
    public void servletReplies() throws Exception {
        System.out.println("servletReplies");
        URL url = new URL("http://127.0.0.1:8080/sample/servlet/check");
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");
        BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
        String result = reader.readLine();
        System.out.println(result);
        assertEquals("yes it works", result);
        conn.disconnect();
    }

    @Test 
    public void succeeds() {}

}
